name: Build Multi-Platform Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact-name: PhiChartSearch_linux_x64
          - os: windows-latest
            artifact-name: PhiChartSearch_windows_x64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 根据项目实际Python版本调整

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # 安装项目依赖

    - name: Check font file existence (Linux)
      run: |
        if [ -f "Source Han Sans & Saira Hybrid-Regular #2934.ttf" ]; then
          echo "Font file found"
        else
          echo "Error: Font file not found!"
          exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Check font file existence (Windows)
      run: |
        if exist "Source Han Sans & Saira Hybrid-Regular #2934.ttf" (
          echo Font file found
        ) else (
          echo Error: Font file not found!
          exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Build with PyInstaller (Linux)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" \
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf:." \
          ChartAnalyzer.py
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Build with PyInstaller (Windows)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" ^
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf;." ^
          ChartAnalyzer.py
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: |
          dist/PhiChartSearch*
          !dist/*.spec