name: Build Multi-Platform Binaries

# 手动触发工作流，需要输入版本号
on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（例如：v1.0.0）'
        required: true
        type: string

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            system: linux
            ext: ''
          - os: windows-latest
            system: windows
            ext: '.exe'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 根据项目实际Python版本调整

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Check font file existence (Linux)
      run: |
        if [ -f "Source Han Sans & Saira Hybrid-Regular #2934.ttf" ]; then
          echo "Font file found"
        else
          echo "Error: Font file not found!"
          exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Check font file existence (Windows)
      run: |
        if exist "Source Han Sans & Saira Hybrid-Regular #2934.ttf" (
          echo Font file found
        ) else (
          echo Error: Font file not found!
          exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Build with PyInstaller (Linux)
      run: |
        # 构建基础二进制文件
        pyinstaller --onefile --windowed --name="PhiChartSearch" \
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf:." \
          ChartAnalyzer.py
        # 重命名二进制文件（添加版本号和系统信息）
        mv dist/PhiChartSearch dist/PhiChartSearch_${{ github.event.inputs.version }}_${{ matrix.system }}_x64
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Build with PyInstaller (Windows)
      run: |
        # 构建基础二进制文件
        pyinstaller --onefile --windowed --name="PhiChartSearch" ^
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf;." ^
          ChartAnalyzer.py
        # 重命名二进制文件（添加版本号和系统信息）
        ren dist\PhiChartSearch.exe PhiChartSearch_${{ github.event.inputs.version }}_${{ matrix.system }}_x64.exe
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # 压缩包名称包含版本号和系统信息
        name: PhiChartSearch_${{ github.event.inputs.version }}_${{ matrix.system }}_x64
        path: |
          dist/PhiChartSearch_${{ github.event.inputs.version }}_${{ matrix.system }}_x64${{ matrix.ext }}
          !dist/*.spec