name: Build & Release Multi-Platform Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（例如：v1.0.0）'
        required: true
        type: string
      publish_release:
        description: '是否发布到GitHub Releases'
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            system: linux
            ext: ''
            asset-name: PhiChartSearch_${{ github.event.inputs.version }}_linux_x64
          - os: windows-latest
            system: windows
            ext: '.exe'
            asset-name: PhiChartSearch_${{ github.event.inputs.version }}_windows_x64.exe

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 调整为项目实际Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Check font file (Linux)
      run: |
        if [ -f "Source Han Sans & Saira Hybrid-Regular #2934.ttf" ]; then
          echo "Font file found"
        else
          echo "Error: Font file not found!" && exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Check font file (Windows)
      run: |
        if exist "Source Han Sans & Saira Hybrid-Regular #2934.ttf" (
          echo Font file found
        ) else (
          echo Error: Font file not found! && exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Build & rename (Linux)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" \
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf:." \
          ChartAnalyzer.py
        mv dist/PhiChartSearch "dist/${{ matrix.asset-name }}"
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Build & rename (Windows)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" ^
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf;." ^
          ChartAnalyzer.py
        ren "dist\PhiChartSearch.exe" "${{ matrix.asset-name }}"
      if: matrix.os == 'windows-latest'
      shell: cmd

    # 直接上传二进制文件（不压缩为ZIP）
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset-name }}  #  artifact名称与二进制文件一致
        path: dist/${{ matrix.asset-name }}
        if-no-files-found: error  # 若文件不存在则报错

    # 发布到Release（直接上传二进制文件）
    - name: Upload to Release
      if: ${{ github.event.inputs.publish_release == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        files: dist/${{ matrix.asset-name }}  # 直接指定二进制文件路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}