name: 构建与发布 PyQT 版 ChartAnalyzer

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（例如：v1.0.0）'
        required: true
        type: string
      publish_release:
        description: '是否发布到GitHub Releases'
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: 在 ${{ matrix.os }} 上构建 PyQT 版
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            system: linux
            ext: ''
            asset-name: PyQT_PhiChartSearch_${{ github.event.inputs.version }}_linux_x64
          - os: windows-latest
            system: windows
            ext: '.exe'
            asset-name: PyQT_PhiChartSearch_${{ github.event.inputs.version }}_windows_x64.exe
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: 验证 QT_ChartAnalyzer.py 存在（Linux）
      run: |
        if [ -f "QT_ChartAnalyzer.py" ]; then
          echo "找到 QT_ChartAnalyzer.py"
        else
          echo "错误：未找到 QT_ChartAnalyzer.py！请确认文件名是否正确" && exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: 验证 QT_ChartAnalyzer.py 存在（Windows）
      run: |
        if exist "QT_ChartAnalyzer.py" (
          echo 找到 QT_ChartAnalyzer.py
        ) else (
          echo 错误：未找到 QT_ChartAnalyzer.py！请确认文件名是否正确 && exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: 配置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: 检查图标文件（Linux）
      run: |
        if [ -f "icon.ico" ]; then
          echo "图标文件存在"
        else
          echo "错误：未找到 icon.ico！" && exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: 检查图标文件（Windows）
      run: |
        if exist "icon.ico" (
          echo 图标文件存在
        ) else (
          echo 错误：未找到 icon.ico！ && exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: 构建并命名（Linux，仅含图标）
      run: |
        pyinstaller --onefile --windowed \
          --name="${{ matrix.asset-name }}" \
          --icon="icon.ico" \
          ./QT_ChartAnalyzer.py
        echo "Linux 构建产物："
        ls -l dist/
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: 构建并命名（Windows，仅含图标）
      run: |
        pyinstaller --onefile --windowed ^
          --name="${{ matrix.asset-name }}" ^
          --icon="icon.ico" ^
          .\QT_ChartAnalyzer.py
        echo Windows 构建产物：
        dir dist\
      if: matrix.os == 'windows-latest'
      shell: cmd  # 严格使用cmd，移除所有#注释

    - name: 上传二进制产物
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset-name }}
        path: |
          dist/${{ matrix.asset-name }}
          dist/${{ matrix.asset-name }}${{ matrix.ext }}
        if-no-files-found: error

  release:
    needs: build
    if: ${{ github.event.inputs.publish_release == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: 发布 PyQT 版 ${{ github.event.inputs.version }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载所有产物
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: 列出下载的产物（调试用）
        run: |
          echo "下载的产物结构："
          ls -lR ./artifacts
        shell: bash

      - name: 创建或使用 PyQt 标签
        run: |
          if ! git tag | grep -q "^PyQt$"; then
            git tag PyQt
            git push origin PyQt
            echo "创建 PyQt 标签"
          else
            echo "PyQt 标签已存在，直接使用"
          fi
        shell: bash

      - name: 上传到 Release（使用 PyQt 标签）
        uses: softprops/action-gh-release@v2
        with:
          tag_name: PyQt
          name: PyQT 版发布 ${{ github.event.inputs.version }}
          body_path: release.md
          files: |
            ./artifacts/PyQT_PhiChartSearch_${{ github.event.inputs.version }}_linux_x64/*
            ./artifacts/PyQT_PhiChartSearch_${{ github.event.inputs.version }}_windows_x64.exe/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}