name: Build & Release Multi-Platform Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（例如：v1.0.0）'
        required: true
        type: string
      publish_release:
        description: '是否发布到GitHub Releases'
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            system: linux
            ext: ''
            asset-name: PhiChartSearch_${{ github.event.inputs.version }}_linux_x64
          - os: windows-latest
            system: windows
            ext: '.exe'
            asset-name: PhiChartSearch_${{ github.event.inputs.version }}_windows_x64.exe
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Check font file (Linux)
      run: |
        if [ -f "Source Han Sans & Saira Hybrid-Regular #2934.ttf" ]; then
          echo "Font file found"
        else
          echo "Error: Font file not found!" && exit 1
        fi
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Check font file (Windows)
      run: |
        if exist "Source Han Sans & Saira Hybrid-Regular #2934.ttf" (
          echo Font file found
        ) else (
          echo Error: Font file not found! && exit 1
        )
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Build & rename (Linux)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" \
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf:." \
          ChartAnalyzer.py
        # 确认构建产物路径
        ls -l dist/
        mv dist/PhiChartSearch "dist/${{ matrix.asset-name }}"
        # 确认重命名后的文件
        ls -l dist/
      if: matrix.os == 'ubuntu-latest'
      shell: bash

    - name: Build & rename (Windows)
      run: |
        pyinstaller --onefile --windowed --name="PhiChartSearch" ^
          --add-data "Source Han Sans & Saira Hybrid-Regular #2934.ttf;." ^
          ChartAnalyzer.py
        # 确认构建产物路径
        dir dist/
        ren "dist\PhiChartSearch.exe" "${{ matrix.asset-name }}"
        # 确认重命名后的文件
        dir dist/
      if: matrix.os == 'windows-latest'
      shell: cmd

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset-name }}
        path: dist/${{ matrix.asset-name }}
        if-no-files-found: error
      # 上传后显示artifact信息
      continue-on-error: false

  release:
    needs: build
    if: ${{ github.event.inputs.publish_release == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts  # 下载到当前目录的artifacts文件夹
          merge-multiple: true  # 合并多个artifact到同一目录

      - name: List downloaded artifacts
        run: |
          # 显示下载的文件列表，用于调试路径
          ls -lR ./artifacts

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body_path: release.md  # 正确读取摘要
          # 直接指定artifact文件的绝对路径
          files: |
            ./artifacts/PhiChartSearch_${{ github.event.inputs.version }}_linux_x64
            ./artifacts/PhiChartSearch_${{ github.event.inputs.version }}_windows_x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}